apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "5"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"control-plane":"controller-manager"},"name":"poison-pill-controller-manager","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"control-plane":"controller-manager"}},"template":{"metadata":{"labels":{"control-plane":"controller-manager"}},"spec":{"containers":[{"args":["--secure-listen-address=0.0.0.0:8443","--upstream=http://127.0.0.1:8080/","--logtostderr=true","--v=10"],"image":"gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0","name":"kube-rbac-proxy","ports":[{"containerPort":8443,"name":"https"}]},{"args":["--metrics-addr=127.0.0.1:8080","--enable-leader-election"],"command":["/manager"],"env":[{"name":"TBD","value":"machine1"}],"image":"quay.io/nyehia/poison-pill:v0.0.1","name":"manager","resources":{"limits":{"cpu":"100m","memory":"30Mi"},"requests":{"cpu":"100m","memory":"20Mi"}}}],"terminationGracePeriodSeconds":10}}}}
    creationTimestamp: 2020-08-18T09:30:17Z
    generation: 5
    labels:
      control-plane: controller-manager
    name: poison-pill-controller-manager
    namespace: default
    resourceVersion: "476985"
    selfLink: /apis/apps/v1/namespaces/default/deployments/poison-pill-controller-manager
    uid: 65515414-6ac7-4bb4-81f4-e51176867796
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        control-plane: controller-manager
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          control-plane: controller-manager
      spec:
        containers:
        - args:
          - --secure-listen-address=0.0.0.0:8443
          - --upstream=http://127.0.0.1:8080/
          - --logtostderr=true
          - --v=10
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
          imagePullPolicy: Always
          name: kube-rbac-proxy
          ports:
          - containerPort: 8443
            name: https
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - args:
          - --metrics-addr=127.0.0.1:8080
          - --enable-leader-election
          command:
          - /manager
          env:
          - name: TBD
            value: machine1
          image: quay.io/nyehia/poison-pill:v0.0.1
          imagePullPolicy: Always
          name: manager
          ports:
          - containerPort: 30001
            hostPort: 30001
            name: p-pill-port
            protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 10
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2020-08-18T09:30:17Z
      lastUpdateTime: 2020-08-19T09:00:07Z
      message: ReplicaSet "poison-pill-controller-manager-5ddc6d6786" has successfully
        progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: 2020-08-20T10:08:29Z
      lastUpdateTime: 2020-08-20T10:08:29Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 5
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
