apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    rbac.ext-remediation/aggregate-to-ext-remediation: "true"
  name: self-node-ext-remediation
rules:
- apiGroups:
  - self-node.medik8s.io
  resources:
  - selfnoderemediationtemplates
  verbs:
  - get
- apiGroups:
  - self-node.medik8s.io
  resources:
  - selfnoderemediations
  verbs:
  - get
  - list
  - create
  - delete
