apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ext-remediation
  labels:
    rbac.ext-remediation/aggregate-to-ext-remediation: "true"
rules:
  - apiGroups:
      - self-node.medik8s.io
    resources:
      - selfnoderemediationtemplates
    verbs:
      - get
  - apiGroups:
      - self-node.medik8s.io
    resources:
      - selfnoderemediations
    verbs:
      - get
      - list
      - create
      - delete

