# permissions for end users to view selfnoderemediationtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: selfnoderemediationtemplate-viewer-role
rules:
- apiGroups:
  - self-node.medik8s.io
  resources:
  - selfnoderemediationtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - self-node.medik8s.io
  resources:
  - selfnoderemediationtemplates/status
  verbs:
  - get
