# permissions for end users to edit selfnodeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: selfnodeconfig-editor-role
rules:
- apiGroups:
  - self-node.medik8s.io
  resources:
  - selfnodeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - self-node.medik8s.io
  resources:
  - selfnodeconfigs/status
  verbs:
  - get
