# permissions for end users to view selfnodeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: selfnodeconfig-viewer-role
rules:
- apiGroups:
  - self-node.medik8s.io
  resources:
  - selfnodeconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - self-node.medik8s.io
  resources:
  - selfnodeconfigs/status
  verbs:
  - get
