# permissions for end users to view selfnoderemediations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: selfnoderemediation-viewer-role
rules:
- apiGroups:
  - self-node.medik8s.io
  resources:
  - selfnoderemediations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - self-node.medik8s.io
  resources:
  - selfnoderemediations/status
  verbs:
  - get
