# permissions for end users to edit selfnoderemediations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: selfnoderemediation-editor-role
rules:
- apiGroups:
  - self-node.medik8s.io
  resources:
  - selfnoderemediations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - self-node.medik8s.io
  resources:
  - selfnoderemediations/status
  verbs:
  - get
