# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/self-node.medik8s.io_selfnoderemediations.yaml
- bases/self-node.medik8s.io_selfnoderemediationtemplates.yaml
- bases/self-node.medik8s.io_selfnodeconfigs.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_selfnoderemediations.yaml
#- patches/webhook_in_selfnoderemediationtemplates.yaml
#- patches/webhook_in_selfnodeconfigs.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_selfnoderemediations.yaml
#- patches/cainjection_in_selfnoderemediationtemplates.yaml
#- patches/cainjection_in_selfnodeconfigs.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
